/*
 *
 *
 *
 *
 *
 *         WARNING: Editing this file may prevent future updates via schematics.
 *                  To maintain easy upgradability, do not edit this file.
 *
 *
 *
 *
 *
 */
import { NgModule } from '@angular/core';
import { BankAdminWorkspaceRoutesModule } from './bank-admin-workspace-routes.module';
import { bankAdminWorkspaceModuleImports } from './bank-admin-workspace-module-imports';
import { Sidebar } from '@backbase/employee-web-app-shared-ui-layout';
import { BankAdminWorkspaceNavigationComponent } from './navigation/bank-admin-workspace-navigation.component';
import { RouterModule } from '@angular/router';
import { CommonModule } from '@angular/common';
import { EntitlementsModule } from '@backbase/foundation-ang/entitlements';

export const sidebar = new Sidebar(BankAdminWorkspaceNavigationComponent);

@NgModule({
  imports: [
    EntitlementsModule,
    BankAdminWorkspaceRoutesModule,
    RouterModule,
    CommonModule,
    ...bankAdminWorkspaceModuleImports,
  ],
  declarations: [BankAdminWorkspaceNavigationComponent],
  providers: [{ provide: Sidebar, useValue: sidebar }],
})
export class BankAdminWorkspaceLoaderModule {}
