apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "employee-app.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "employee-app.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      {{- include "employee-app.labels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        timestamp: {{ now | quote }}
      labels:
        {{- include "employee-app.labels" . | nindent 8 }}
        {{- with .Values.podTemplate.annotations }}  
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsGroup: 65532
        runAsUser: 65532
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: AUTH_URL
            valueFrom:
              secretKeyRef:
                name: "{{ include "employee-app.name" . }}"
                key: "AUTH_URL"
          - name: AWS_REGION
            valueFrom:
              secretKeyRef:
                name: "{{ include "employee-app.name" . }}"
                key: "AWS_REGION"
          - name: AUTH_REALM
            valueFrom:
              secretKeyRef:
                name: "{{ include "employee-app.name" . }}"
                key: "AUTH_REALM"
          - name: AUTH_LANDING_PAGE
            valueFrom:
              secretKeyRef:
                name: "{{ include "employee-app.name" . }}"
                key: "AUTH_LANDING_PAGE"
          - name: API_ROOT
            valueFrom:
              secretKeyRef:
                name: "{{ include "employee-app.name" . }}"
                key: "API_ROOT"                
          {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 10 }}
          {{- end }}       
          {{- if .Values.autoscaling.enabled }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - employee-app
        ip: 127.0.0.1
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30