/*
 *
 *
 *
 *
 *
 *         WARNING: Editing this file may prevent future updates via schematics.
 *                  To maintain easy upgradability, do not edit this file.
 *
 *
 *
 *
 *
 */
import { NgModule } from '@angular/core';
import { CustomerSupportWorkspaceRoutesModule } from './customer-support-workspace-routes.module';
import { customerSupportWorkspaceModuleImports } from './customer-support-workspace-module-imports';
import { RouterModule } from '@angular/router';
import { CustomerSupportWorkspaceNavigationComponent } from './navigation/customer-support-workspace-navigation.component';
import { Sidebar } from '@backbase/employee-web-app-shared-ui-layout';
import { EntitlementsModule } from '@backbase/foundation-ang/entitlements';
import { CommonModule } from '@angular/common';
import { TooltipModule } from '@backbase/ui-ang/tooltip-directive';

export const sidebar = new Sidebar(CustomerSupportWorkspaceNavigationComponent);

@NgModule({
  imports: [
    EntitlementsModule,
    CustomerSupportWorkspaceRoutesModule,
    RouterModule,
    ...customerSupportWorkspaceModuleImports,
    CommonModule,
    TooltipModule,
  ],
  declarations: [CustomerSupportWorkspaceNavigationComponent],
  providers: [{ provide: Sidebar, useValue: sidebar }],
})
export class CustomerSupportWorkspaceLoaderModule {}
