/*
 *
 *
 *
 *
 *
 *         WARNING: Editing this file may prevent future updates via schematics.
 *                  To maintain easy upgradability, do not edit this file.
 *
 *
 *
 *
 *
 */
import { NgModule } from '@angular/core';
import { ServiceAgreementModeRoutesModule } from './service-agreement-mode-routes.module';
import { serviceAgreementModeModuleImports } from './service-agreement-mode-module-imports';
import { ServiceAgreementModeNavigationComponent } from './navigation/service-agreement-mode-navigation.component';
import { RouterModule } from '@angular/router';
import { EmployeeWebAppLayoutModule, Sidebar } from '@backbase/employee-web-app-shared-ui-layout';
import { EntitlementsModule } from '@backbase/foundation-ang/entitlements';

export const sidebar = new Sidebar(ServiceAgreementModeNavigationComponent);

@NgModule({
  imports: [
    EntitlementsModule,
    EmployeeWebAppLayoutModule,
    ServiceAgreementModeRoutesModule,
    RouterModule,
    ...serviceAgreementModeModuleImports,
  ],
  declarations: [ServiceAgreementModeNavigationComponent],
  providers: [{ provide: Sidebar, useValue: sidebar }],
})
export class ServiceAgreementModeLoaderModule {}
